language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href https://tmk2003.github.io/Im-Generic-Username/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/im-generic-username
  on:
    branch: master
